name: Basic "Hello World" example

on:
    pull_request:
    push:

jobs:
  compile_it:
      name: Basic setup and compile
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v4
      - name: CMake compile
        shell: pwsh
        run: |
          cmake -S . -B cmake/build-windows -G "Visual Studio 17 2022"
          cmake --build cmake/build-windows --config Release
      - name: Within script
        run: |
          .\compile.ps1
